version: '3'
services:
     web:
       build:
         context: .
         dockerfile: Dockerfile.dev
       ports:
         - "3000:3000"
       volumes:
           - /app/node_modules
           - .:/app
     thiea_test:
           image: theiaide/theia:latest
           volumes:
              - .:/home/project
           ports:
              - "4500:3000"
           user: node
